Added two methods incrementEach and decrementEach
mongodb/laravel-mongodb pull request #2550
Opened 2023-07-01 14:56 UTC by SmallRuralDog

add incrementEach
add decrementEach

2023-08-25 15:38 UTC, GromNaN commented
Hello, thanks for the suggestion. For reference, this methods were added in Laravel 9 by https://github.com/laravel/framework/pull/45577.

Would you like to rebase the PR, add tests in [`QueryBuilderTest`](https://github.com/jenssegers/laravel-mongodb/blob/master/tests/QueryBuilderTest.php) and update the changelog?

2023-08-25 15:47 UTC, GromNaN commented on src/Query/Builder.php
> +                $query->orWhereNotNull($column);
With cumulative conditions on all fields, no field will be incremented if at least 1 of the fields is `null`.

We'd be wise not to set any conditions at all and let the server return an error.

2023-08-28 07:24 UTC, alcaeus requested changes
Please address the comment by @GromNaN and add tests for the new functionality.

2024-07-22 09:44 UTC, GromNaN approved these changes

2024-07-22 09:45 UTC, GromNaN commented
PR updated with tests.

2024-07-22 12:53 UTC, alcaeus reviewed
Minor suggestion to optimise the `$add` operator, but I like that the behaviour now better matches the expectation from Laravel that all documents are updated and we gracefully handle `null` values.

2024-07-22 12:53 UTC, alcaeus commented on src/Query/Builder.php
> +                '$add' => [['$ifNull' => ['$' . $column, 0]], $amount],
According to the [docs](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/), there's an optimisation we can leverage in MongoDB 6.1 and later:
> Starting in MongoDB 6.1 you can optimize the `$add` operation. To improve performance, group references at the end of the argument list.

```suggestion
                '$add' => [$amount, ['$ifNull' => ['$' . $column, 0]]],
```

2024-07-22 13:10 UTC, GromNaN commented on src/Query/Builder.php
> +                '$add' => [['$ifNull' => ['$' . $column, 0]], $amount],
Thanks. It's strange that the server isn't able to apply this kind of optimisation itself.

2024-07-22 13:11 UTC, alcaeus approved these changes

2024-07-22 13:14 UTC, merged